  CREATE TABLE "IBTM_CLIENTES" 
   (	"CO_TIPO_DOC_IDE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"NU_DOC_CLIENTE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ID_DEDO_DER" NUMBER, 
	"ID_DEDO_IZQ" NUMBER, 
	"AP_PAT_CLIENTE" VARCHAR2(120 BYTE), 
	"AP_MAT_CLIENTE" VARCHAR2(120 BYTE), 
	"NO_CLIENTE" VARCHAR2(120 BYTE), 
	"BL_TEMPLATE_DER" BLOB, 
	"BL_TEMPLATE_IZQ" BLOB, 
	"BL_WSQ_DER" BLOB, 
	"BL_WSQ_IZQ" BLOB, 
	"IN_CALIDAD_DER" NUMBER(*,0), 
	"IN_CALIDAD_IZQ" NUMBER(*,0), 
	"FE_CREA" DATE, 
	"CO_USU_CREA" VARCHAR2(20 BYTE), 
	"FE_ACTUALIZA" DATE, 
	"CO_USU_ACT" VARCHAR2(20 BYTE), 
	"NU_CLIENTE" VARCHAR2(8 BYTE), 
	"ES_CLIENTE" CHAR(1 BYTE), 
	 CONSTRAINT "PK_IBTM_CLIENTES" PRIMARY KEY ("NU_DOC_CLIENTE", "CO_TIPO_DOC_IDE")) ;

  CREATE INDEX "IX_IBTM_CLI_001" ON "IBTM_CLIENTES" ("ID_DEDO_DER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  CREATE INDEX "IX_IBTM_CLI_002" ON "IBTM_CLIENTES" ("ID_DEDO_IZQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

  
  
  CREATE TABLE "IBTV_MOVIMIENTO" 
   (	"ID_TXN" NUMBER(16,0) NOT NULL ENABLE, 
	"NU_DOC_CLIENT" VARCHAR2(15 BYTE), 
	"FE_INI_SERVER" DATE, 
	"FE_FIN_SERVER" DATE, 
	"FE_INI_CLIENT" DATE, 
	"FE_FIN_CLIENT" DATE, 
	"IP_CLIENT" VARCHAR2(20 BYTE), 
	"FE_TXN" DATE, 
	"US_TXN" VARCHAR2(20 BYTE), 
	"ID_BIODB" NUMBER(*,0), 
	"IN_RESTRICCION" VARCHAR2(2 BYTE), 
	"IN_VIGENCIA" NUMBER(*,0), 
	"IN_GRUPO_REST" NUMBER, 
	"ID_DEDO_DER" NUMBER, 
	"ID_DEDO_IZQ" NUMBER, 
	"IN_CALIDAD_DER" NUMBER(*,0), 
	"IN_VERIFICACION" VARCHAR2(20 BYTE), 
	"CO_ERROR" NUMBER, 
	"CO_ERROR_RENIEC" NUMBER, 
	"CO_TIPOTXN" NUMBER, 
	"CO_TIPO_DOC_IDE" CHAR(1 BYTE), 
	"IN_CALIDAD_IZQ" NUMBER(*,0), 
	"CO_TIPO_CANAL" NUMBER, 
	"CO_TIPO_OPERACION" NUMBER, 
	"CO_TIPO_VALIDA" NUMBER, 
	"CO_UNIDAD" VARCHAR2(8 BYTE), 
	"ID_TXN_PADRE" NUMBER(16,0), 
	"CO_TIPO_NOTIFICACION" NUMBER, 
	"BL_WSQ_DER" BLOB, 
	"BL_WSQ_IZQ" BLOB, 
	"NO_TERMINAL" VARCHAR2(20 BYTE), 
	"NU_CLIENTE" VARCHAR2(8 BYTE), 
	"NU_DNI_AUTORIZADO" VARCHAR2(8 BYTE), 
	"ES_MOVIMIENTO" CHAR(1 BYTE), 
	"FE_ACTUALIZA" DATE, 
	"CO_USU_ACT" VARCHAR2(20 BYTE), 
	"BL_TEMPLATE_DER" BLOB, 
	"BL_TEMPLATE_IZQ" BLOB, 
	 CONSTRAINT "PK_IBTV_MOVIMIENTO" PRIMARY KEY ("ID_TXN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   )

  
  