
  CREATE TABLE "GWYBIO"."IBTM_CLIENTES" 
   (	"CO_TIPO_DOC_IDE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"NU_DOC_CLIENTE" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
	"ID_DEDO_DER" NUMBER, 
	"ID_DEDO_IZQ" NUMBER, 
	"AP_PAT_CLIENTE" VARCHAR2(120 BYTE), 
	"AP_MAT_CLIENTE" VARCHAR2(120 BYTE), 
	"NO_CLIENTE" VARCHAR2(120 BYTE), 
	"BL_TEMPLATE_DER" BLOB, 
	"BL_TEMPLATE_IZQ" BLOB, 
	"BL_WSQ_DER" BLOB, 
	"BL_WSQ_IZQ" BLOB, 
	"IN_CALIDAD_DER" NUMBER(*,0), 
	"IN_CALIDAD_IZQ" NUMBER(*,0), 
	"FE_CREA" DATE, 
	"CO_USU_CREA" VARCHAR2(20 BYTE), 
	"FE_ACTUALIZA" DATE, 
	"CO_USU_ACT" VARCHAR2(20 BYTE), 
	"NU_CLIENTE" VARCHAR2(8 BYTE), 
	"ES_CLIENTE" CHAR(1 BYTE), 
	 CONSTRAINT "PK_IBTM_CLIENTES" PRIMARY KEY ("NU_DOC_CLIENTE", "CO_TIPO_DOC_IDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GWYBIO_DAT"  ENABLE, 
	 CONSTRAINT "FK_IBTM_CLI_IBTD_CAL_NIST_01" FOREIGN KEY ("IN_CALIDAD_IZQ")
	  REFERENCES "GWYBIO"."IBTD_CALIDAD_NISTTIR" ("IN_CALIDAD") ENABLE, 
	 CONSTRAINT "FK_IBTM_CLI_IBTD_CAL_NIST_02" FOREIGN KEY ("IN_CALIDAD_DER")
	  REFERENCES "GWYBIO"."IBTD_CALIDAD_NISTTIR" ("IN_CALIDAD") ENABLE, 
	 CONSTRAINT "FK_IBTM_CLI_IBTD_TIP_DEDO_01" FOREIGN KEY ("ID_DEDO_DER")
	  REFERENCES "GWYBIO"."IBTD_TIPO_DEDO" ("ID_DEDO") ENABLE, 
	 CONSTRAINT "FK_IBTM_CLI_IBTD_TIP_DEDO_02" FOREIGN KEY ("ID_DEDO_IZQ")
	  REFERENCES "GWYBIO"."IBTD_TIPO_DEDO" ("ID_DEDO") ENABLE, 
	 CONSTRAINT "FK_IBTM_CLI_IBTR_TIP_DOC_ID" FOREIGN KEY ("CO_TIPO_DOC_IDE")
	  REFERENCES "GWYBIO"."IBTR_TIP_DOC_IDENTIDAD" ("CO_TIPO_DOC_IDE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GWYBIO_DAT" 
 LOB ("BL_TEMPLATE_DER") STORE AS BASICFILE (
  TABLESPACE "GWYBIO_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BL_TEMPLATE_IZQ") STORE AS BASICFILE (
  TABLESPACE "GWYBIO_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BL_WSQ_DER") STORE AS BASICFILE (
  TABLESPACE "GWYBIO_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("BL_WSQ_IZQ") STORE AS BASICFILE (
  TABLESPACE "GWYBIO_DAT" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE INDEX "GWYBIO"."IX_IBTM_CLI_001" ON "GWYBIO"."IBTM_CLIENTES" ("ID_DEDO_DER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GWYBIO_DAT" ;

  CREATE INDEX "GWYBIO"."IX_IBTM_CLI_002" ON "GWYBIO"."IBTM_CLIENTES" ("ID_DEDO_IZQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GWYBIO_DAT" ;
